connections:
  - alias: gestao_projetos
    driver: mysql
    proto: tcp
    user: root
    passwd: "4Hg428u$@"
    host: 127.0.0.1
    port: 3306
    dbName: KANBOARDPACTORJ
    params:
      tls: skip-verify
